<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" total="6" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="SivaTests" duration-ms="51479" started-at="2018-08-14T14:30:10Z" finished-at="2018-08-14T14:31:01Z">
    <groups>
    </groups>
    <test name="SivaTests" duration-ms="51479" started-at="2018-08-14T14:30:10Z" finished-at="2018-08-14T14:31:01Z">
      <class name="tests.Test002">
        <test-method status="PASS" signature="flipkart_test()[pri:0, instance:tests.Test002@7205765b]" name="flipkart_test" duration-ms="7708" started-at="2018-08-14T20:00:39Z" finished-at="2018-08-14T20:00:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- flipkart_test -->
        <test-method status="PASS" signature="getTestResult(org.testng.ITestResult)[pri:0, instance:tests.Test002@7205765b]" name="getTestResult" is-config="true" duration-ms="1" started-at="2018-08-14T20:00:47Z" finished-at="2018-08-14T20:00:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=flipkart_test status=SUCCESS method=Test002.flipkart_test()[pri:0, instance:tests.Test002@7205765b] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getTestResult -->
        <test-method status="PASS" signature="jabong_test()[pri:0, instance:tests.Test002@7205765b]" name="jabong_test" duration-ms="5420" started-at="2018-08-14T20:00:47Z" finished-at="2018-08-14T20:00:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- jabong_test -->
        <test-method status="PASS" signature="getTestResult(org.testng.ITestResult)[pri:0, instance:tests.Test002@7205765b]" name="getTestResult" is-config="true" duration-ms="0" started-at="2018-08-14T20:00:52Z" finished-at="2018-08-14T20:00:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=jabong_test status=SUCCESS method=Test002.jabong_test()[pri:0, instance:tests.Test002@7205765b] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getTestResult -->
        <test-method status="FAIL" signature="myntra_test()[pri:0, instance:tests.Test002@7205765b]" name="myntra_test" duration-ms="8103" started-at="2018-08-14T20:00:52Z" finished-at="2018-08-14T20:01:00Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at tests.Test002.myntra_test(Test002.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- myntra_test -->
        <test-method status="PASS" signature="getTestResult(org.testng.ITestResult)[pri:0, instance:tests.Test002@7205765b]" name="getTestResult" is-config="true" duration-ms="947" started-at="2018-08-14T20:01:00Z" finished-at="2018-08-14T20:01:01Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=myntra_test status=FAILURE method=Test002.myntra_test()[pri:0, instance:tests.Test002@7205765b] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getTestResult -->
      </class> <!-- tests.Test002 -->
      <class name="tests.Test001">
        <test-method status="PASS" signature="reportBegin()[pri:0, instance:tests.Test001@7133da86]" name="reportBegin" is-config="true" duration-ms="194" started-at="2018-08-14T20:00:09Z" finished-at="2018-08-14T20:00:10Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportBegin -->
        <test-method status="PASS" signature="bing_test()[pri:0, instance:tests.Test001@7133da86]" name="bing_test" duration-ms="1110" started-at="2018-08-14T20:00:10Z" finished-at="2018-08-14T20:00:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- bing_test -->
        <test-method status="PASS" signature="getTestResult(org.testng.ITestResult)[pri:0, instance:tests.Test001@7133da86]" name="getTestResult" is-config="true" duration-ms="1" started-at="2018-08-14T20:00:11Z" finished-at="2018-08-14T20:00:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=bing_test status=SUCCESS method=Test001.bing_test()[pri:0, instance:tests.Test001@7133da86] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getTestResult -->
        <test-method status="PASS" signature="google_test()[pri:0, instance:tests.Test001@7133da86]" name="google_test" duration-ms="2398" started-at="2018-08-14T20:00:11Z" finished-at="2018-08-14T20:00:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- google_test -->
        <test-method status="PASS" signature="getTestResult(org.testng.ITestResult)[pri:0, instance:tests.Test001@7133da86]" name="getTestResult" is-config="true" duration-ms="0" started-at="2018-08-14T20:00:13Z" finished-at="2018-08-14T20:00:13Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=google_test status=SUCCESS method=Test001.google_test()[pri:0, instance:tests.Test001@7133da86] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getTestResult -->
        <test-method status="FAIL" signature="yahoo_test()[pri:0, instance:tests.Test001@7133da86]" name="yahoo_test" duration-ms="24823" started-at="2018-08-14T20:00:13Z" finished-at="2018-08-14T20:00:38Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at tests.Test001.yahoo_test(Test001.java:66)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:379)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:340)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:125)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:413)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- yahoo_test -->
        <test-method status="PASS" signature="getTestResult(org.testng.ITestResult)[pri:0, instance:tests.Test001@7133da86]" name="getTestResult" is-config="true" duration-ms="930" started-at="2018-08-14T20:00:38Z" finished-at="2018-08-14T20:00:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=yahoo_test status=FAILURE method=Test001.yahoo_test()[pri:0, instance:tests.Test001@7133da86] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getTestResult -->
        <test-method status="PASS" signature="reportEnd()[pri:0, instance:tests.Test001@7133da86]" name="reportEnd" is-config="true" duration-ms="730" started-at="2018-08-14T20:01:01Z" finished-at="2018-08-14T20:01:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reportEnd -->
      </class> <!-- tests.Test001 -->
    </test> <!-- SivaTests -->
  </suite> <!-- SivaTests -->
</testng-results>
